version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - "MONGO_INITDB_DATABASE: restaurant-manager-db"
      - "MONGO_INITDB_ROOT_USERNAME:marcelo"
      - "MONGO_INITDB_ROOT_PASSWORD:marcelo"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - "3000:3000"
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge