version: '3'

services:
  nodejs:
    build:
      context: .
    container_name: nodejs-app
    volumes:
      - .:/usr/src/app
    tty: true
    restart: always
    environment:
      - PORT=3000
      - mongodb_URI=mongodb://mongodb:27017/restaurant-manager-db
    ports:
      - "3000:3000"
    command: yarn dev
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    tty: true
    ports:
      - 27017:27017
    environment:
      - "MONGO_INITDB_DATABASE:restaurant-manager-db"
      - "MONGO_INITDB_ROOT_USERNAME:root"
      - "MONGO_INITDB_ROOT_PASSWORD:toor"
    volumes:
      - ./data:/data/db
    networks:
      - node-network

networks:
  node-network:
    driver: bridge