version: '3'

services:
  node:
    image: node:18-alpine
    container_name: node
    working_dir: /usr/src/app
    networks:
      - backend
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - backend