GET http://localhost:8000/api/posts
Authorization: Bearer 

###

POST http://localhost:8000/api/refreshtoken
Content-Type: application/json

{
    "token": "" 
}

###

POST http://localhost:8000/api/login
Content-Type: application/json

{
    "username": "Jim"
}

###

DELETE http://localhost:8000/api/logout
Content-Type: application/json

{
    "token": ""
}